apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigning
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nats-ca
spec:
  secretName: nats-ca
  duration: 8736h # 1 year
  renewBefore: 240h # 10 days
  issuerRef:
    name: selfsigning
    kind: ClusterIssuer
  commonName: nats-ca
  usages:
    - cert sign
  organization:
    - Red Badger
  isCA: true
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: nats-ca
spec:
  ca:
    secretName: nats-ca
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nats-server-tls
spec:
  secretName: nats-server-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: ClusterIssuer
  usages:
    - signing
    - key encipherment
    - server auth
  organization:
    - Red Badger
  commonName: nats.nats.svc.cluster.local
  dnsNames:
    - nats.nats
    - nats.nats
    - nats.nats.svc
    - nats.nats.svc.cluster.local
    - "*.nats"
    - "*.nats.nats"
    - "*.nats.nats.svc"
---
# TODO: move this into 50-todo-backend/base
# This is just so that `nats-ca` will share its ca.crt public certificate
# into the todo namespace
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: bogus-cert
spec:
  secretName: bogus-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: ClusterIssuer
  usages:
    - signing
  commonName: bogus@example.com
  organization:
    - Bogus
