apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-ca-cert
  namespace: todo
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDGzCCAgOgAwIBAgIRAMqltgJNV5WBw3d5ebJUAMUwDQYJKoZIhvcNAQELBQAw
    JzETMBEGA1UEChMKUmVkIEJhZGdlcjEQMA4GA1UEAxMHbmF0cy1jYTAeFw0yMTA4
    MDkxNDQ5MzlaFw0yMjA4MDgxNDQ5MzlaMCcxEzARBgNVBAoTClJlZCBCYWRnZXIx
    EDAOBgNVBAMTB25hdHMtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDfDzrVzQEA0r5bmV2IZSNW7VbDexQxLnrqAFx11xwk8i1RYQKyS7Gm1K7030CI
    JorkHtyqHncSm5+5pFIhfwmJIJifnhWcVw+8WzIhSS/HTgZHiXOpROVTjQwntMZF
    ibf/3P8z0EFVrffOrOB+7Trf6H7VhCMa1A21edMyOg3rTiiSILLd0Rgu3G6TQRei
    HX2QvHTwnT/SilORLryUNFmjFhIA+CLZnsxDHS8TKqMa5JFUKGNhwMoAFDlCzV1c
    UOP33GAo853C8GCP9fOJ3VlT+Jd/7+uOqzN6OOF96Wq6T5rSnE7lG8BrUgrD1JCh
    nFk9vY5nIAvIlacGc6S9uHYDAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICBDAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdDgQWBBTlDkobwdeHnKzdM7Odzy/XJf36ejANBgkq
    hkiG9w0BAQsFAAOCAQEAnk3VMwvs67dgoCx/0h2Q/4tvjD3tezeFuT4bm3qMUMZL
    3IafzhRoGG/acyiZFGy9XWpildwu2Nlh9Hya28ZF5oEP+gIpnCuyq0lmE4BL7R39
    tyle8t3lakEIWBoOC85EtO5Aax6lRWAYN78896jW+OfoiiQPYn8afpMiY9T03Nr9
    bJ/4d4527Jm7eRVUdpsmtFmNQ9vSvproZ+kUO8o7vxQq1CXQzPb7pwtnbbHZzX3Y
    7g3zid8QYB8J1A00qXPj0yRm6fcBow8yswi8Q7Kk/rs6DPBGIVBrOq15EGI6WDLv
    ZVo4TEN0aWLfhgWVu9zUnzbWRFg8cK0Dgq8XsxyDLw==
    -----END CERTIFICATE-----
