apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-actor
  labels:
    app: actor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actor
  template:
    metadata:
      labels:
        app: actor
    spec:
      containers:
        - name: wasmcloud
          image: eu.gcr.io/wasmcloud-k8s-demo/wasmcloud:0.18.2
          args: ["--manifest=/etc/manifest/manifest.yaml"]
          volumeMounts:
            - name: manifest
              mountPath: "/etc/manifest"
              readOnly: true
      volumes:
        - name: manifest
          configMap:
            name: manifest-actor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manifest-actor
data:
  manifest.yaml: |
    labels:
      sample: "wasmcloud todo-backend actor"
    actors:
      - "eu.gcr.io/wasmcloud-k8s-demo/todo-backend:0.2"
