apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-actor
  labels:
    app: actor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actor
  template:
    metadata:
      labels:
        app: actor
    spec:
      containers:
        - name: wasmcloud
          image: eu.gcr.io/wasmcloud-k8s-demo/wasmcloud:0.18.2
          args: ["--manifest=/etc/manifest/manifest.yaml"]
          volumeMounts:
            - name: manifest
              mountPath: "/etc/manifest"
              readOnly: true
          env:
            - name: CONTROL_HOST
              value: example-nats-cluster
            - name: RPC_HOST
              value: example-nats-cluster
            - name: KVCACHE_NATS_URL
              value: example-nats-cluster
      volumes:
        - name: manifest
          configMap:
            name: manifest-actor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manifest-actor
data:
  manifest.yaml: |
    labels:
      sample: "wasmcloud todo-backend actor"
    actors:
      - "eu.gcr.io/wasmcloud-k8s-demo/todo-backend:0.2"
---
# FIXME: pull this out into another file
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: example-nats-cluster
spec:
  size: 3
  version: "2.1.8"
