apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-actor
  labels:
    app: actor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actor
  template:
    metadata:
      labels:
        app: actor
    spec:
      containers:
        - name: wasmcloud
          image: eu.gcr.io/wasmcloud-k8s-demo/wasmcloud:0.18.2-debug
          imagePullPolicy: Always
          args: ["--manifest=/etc/manifest/manifest.yaml"]
          volumeMounts:
            - name: manifest
              mountPath: "/etc/manifest"
              readOnly: true
          env:
            - name: CONTROL_HOST
              value: nats-cluster.nats-cluster
            - name: RPC_HOST
              value: nats-cluster.nats-cluster
            - name: KVCACHE_NATS_URL
              value: nats-cluster.nats-cluster
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LOG
              value: "debug"
      volumes:
        - name: manifest
          configMap:
            name: manifest-actor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manifest-actor
data:
  # TODO: refer to manifest .yaml by path rather than copy-paste
  manifest.yaml: |
    labels:
      sample: "wasmcloud todo-backend actor"
    actors:
      - "eu.gcr.io/wasmcloud-k8s-demo/todo-backend:0.2"
