apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-redis-capability
  labels:
    app: redis-capability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-capability
  template:
    metadata:
      labels:
        app: redis-capability
    spec:
      containers:
        - name: wasmcloud
          image: eu.gcr.io/wasmcloud-k8s-demo/wasmcloud:0.18.2
          imagePullPolicy: Always
          args: ["--manifest=/etc/manifest/manifest.yaml"]
          volumeMounts:
            - name: manifest
              mountPath: "/etc/manifest"
              readOnly: true
          env:
            - name: CONTROL_HOST
              value: nats-cluster
            - name: RPC_HOST
              value: nats-cluster
            - name: KVCACHE_NATS_URL
              value: nats-cluster
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LOG
              value: "debug"
      volumes:
        - name: manifest
          configMap:
            name: manifest-redis-capability
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manifest-redis-capability
data:
  # TODO: refer to manifest .yaml by path rather than copy-paste
  # TODO: actually deploy a redis
  manifest.yaml: |
    labels:
      sample: "wasmcloud todo-backend redis"
    capabilities:
      - image_ref: wasmcloud.azurecr.io/redis:0.11.2
        link_name: default
