apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-jwt
  namespace: nats
data:
  nats.nats.jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJUU0lFWE9IN0tPVjc3MlhBUDNRSUJKWFRDWFk2RjZXRFFFSEwyTDRaTlBLUTM1V0Q1WktBIiwiaWF0IjoxNjI4NzU2OTQ3LCJpc3MiOiJPRE1EWjNHUVdDWURWWVZOUUZEMjVGNFlRNEhJQ0NKS0RZMk9LRzJRUklZU0U1UURVSU41M09YUSIsIm5hbWUiOiJuYXRzLm5hdHMiLCJzdWIiOiJPRE1EWjNHUVdDWURWWVZOUUZEMjVGNFlRNEhJQ0NKS0RZMk9LRzJRUklZU0U1UURVSU41M09YUSIsIm5hdHMiOnsidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.tNuTjvAPKNlweUc0a14XM2NRfWrtEh4W45p_9x1jKFHc2cuuQReWNoC2uGD-f8YvNrBOYompzmmsQSWoeFrNDQ
    
